# Generated by Django 4.2.7 on 2025-11-02 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('3.1', 'Proof of disposal, maintenance, and inspection'), ('3.2', 'Disposal and self-inspection report'), ('3.3', 'Maintenance report'), ('3.4', 'Report of defects and repairs')], max_length=10)),
                ('data', models.JSONField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='accounts.location')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('2.1', 'Legal approvals and permits'), ('2.2', 'Construction approval or safety certificate'), ('2.3', 'Installation and operation manual'), ('2.4', 'Maintenance certificate'), ('2.5', 'Site plans and schematics'), ('3.5', 'Waste removal record'), ('3.6', 'Inspection report (General inspection)'), ('3.7', 'Record of cleaning and detergents used')], max_length=10)),
                ('file_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.location')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
