# Generated by Django 4.2.7 on 2025-11-05 17:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_formsubmission_documentupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='file_url',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='file',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
    ]
