# Generated by Django 4.2.7 on 2025-11-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_documentupload_file_url_documentupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='file_direct_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
