# Generated by Django 4.2.7 on 2025-11-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_documentupload_file_direct_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='file_direct_url',
        ),
    ]
