# Generated by Django 4.2.7 on 2025-11-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_documentupload_file_direct_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='resource_type',
            field=models.CharField(choices=[('raw', 'Raw'), ('image', 'Image')], default='raw', max_length=10),
        ),
    ]
