# Generated by Django 4.2.7 on 2025-11-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_documentupload_resource_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document Upload', 'verbose_name_plural': 'Document Uploads'},
        ),
    ]
