# Generated by Django 4.2.7 on 2025-11-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_documentupload_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='upload_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('authenticated', 'Authenticated')], default='upload', help_text='Cloudinary upload type - determines URL access method', max_length=15),
        ),
    ]
