# Generated by Django 4.2.7 on 2025-11-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_documentupload_upload_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentupload',
            options={},
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='upload_type',
        ),
    ]
